# These are supported funding model platforms

github: [sh-dv]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: shdvapps
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: # Replace with a single custom sponsorship URL
