/* eslint-disable @next/next/no-sync-scripts */
import Head from "next/head";
import "../public/assets/styles/style.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>{"hat.sh v2 beta"}</title>
        <meta charSet="utf-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icons/favicon.ico" />
      </Head>

      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
